name: Domain Audit
description: Template for domain-specific audit workflow
title: "🔧 Domain Audit: [DOMAIN_NAME]"
labels: ["audit", "refactoring", "domain-specific"]
body:
  - type: markdown
    attributes:
      value: |
        ## Domain Audit Workflow
        
        This issue tracks the comprehensive audit and refactoring of the **[DOMAIN_NAME]** domain.
        
        ### Workflow Overview
        1. **Survey** - Identify all domain-related files
        2. **Plan** - Create detailed refactoring plan for approval
        3. **Execute** - Implement changes with tracking
        4. **Document** - Update documentation
        5. **Report** - Generate completion summary
        
  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Select the domain to audit
      options:
        - admin
        - analytics
        - auth
        - compliance
        - dashboard
        - dispatch
        - ifta
        - onboarding
        - settings
        - vehicles
    validations:
      required: true
      
  - type: checkboxes
    id: survey_tasks
    attributes:
      label: "Phase 1: Survey Tasks"
      options:
        - label: "Identify all domain components"
        - label: "Identify all domain features"
        - label: "Identify all domain actions"
        - label: "Identify all domain fetchers"
        - label: "Identify all domain types"
        - label: "Identify all domain schemas"
        - label: "Identify Prisma schema dependencies"
        - label: "Identify Clerk auth/RBAC dependencies"
        - label: "Map file relationships and dependencies"
        - label: "Generate domain file inventory"
        
  - type: checkboxes
    id: planning_tasks
    attributes:
      label: "Phase 2: Planning Tasks"
      options:
        - label: "Create component organization plan"
        - label: "Create feature organization plan"
        - label: "Identify unused/duplicate files"
        - label: "Plan client/server component separation"
        - label: "Plan actions/fetchers optimization"
        - label: "Plan types/schemas consolidation"
        - label: "Create dependency cleanup plan"
        - label: "Plan documentation updates"
        - label: "Generate approval document"
        
  - type: checkboxes
    id: execution_tasks
    attributes:
      label: "Phase 3: Execution Tasks"
      options:
        - label: "Remove unused files"
        - label: "Deduplicate code"
        - label: "Separate client/server components"
        - label: "Reorganize component folders"
        - label: "Reorganize feature folders"
        - label: "Optimize actions"
        - label: "Optimize fetchers"
        - label: "Consolidate types"
        - label: "Consolidate schemas"
        - label: "Clean up imports/dependencies"
        - label: "Update Prisma schema if needed"
        - label: "Update auth/RBAC configurations"
        
  - type: checkboxes
    id: documentation_tasks
    attributes:
      label: "Phase 4: Documentation Tasks"
      options:
        - label: "Update User Documentation"
        - label: "Update Developer Documentation"
        - label: "Update domain-specific guides"
        - label: "Update architecture diagrams"
        - label: "Update API documentation"
        
  - type: checkboxes
    id: testing_tasks
    attributes:
      label: "Phase 5: Testing & Validation"
      options:
        - label: "Verify all imports resolve"
        - label: "Run type checking"
        - label: "Test domain functionality"
        - label: "Verify auth/permissions"
        - label: "Test database operations"
        - label: "Generate final report"